config/routes.rb
Rails.application.routes.draw do
  post 'add/user', to: 'chats#add_user'
  resources :chats do 
    resources :messages
  end
  devise_for :users
  root 'chats#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    validates :name, presence: true
    has_many :user_chats
    has_many :users, through: :user_chats
    has_many :messages

    after_update_commit :update_chat_details

    private 

    def update_chat_details 
        broadcast_replace_to('chat_details_channel', partial:'shared/chat', locals: { chat: self }, target:"chat_#{id}" )
    end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  after_create_commit :broadcast_chat_messages_create 
  after_update_commit :broadcast_chat_messages_update
  after_destroy_commit :broadcast_chat_messages_destroy

  private 

  def broadcast_chat_messages_create 
      broadcast_append_to('chat_messages_channel', partial:'messages/message', locals: { message: self }, target: "chat_messages_div")
  end

  def  broadcast_chat_messages_update
    broadcast_replace_to('chat_messages_channel', partial:'messages/message', locals: { message: self }, target: "message_#{id}")
  end

  def  broadcast_chat_messages_destroy
    broadcast_remove_to('chat_messages_channel', target: "message_#{id}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :user_chats
         has_many :chats, through: :user_chats
         has_many :messages
end

app/models/user_chat.rb
class UserChat < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  after_create_commit do
    broadcast_append_to_chat
  end

  private

  def broadcast_append_to_chat
    broadcast_append_to(
      'users_chats_channel',
      target: "user_#{user_id}_chats",
      partial: 'shared/chat',
      locals: { chat: Chat.find(chat_id) }
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chat, only: %i[ show edit update destroy ]

  def index
    @chats = Chat.all
  end

  def show
  end

  def new
    @chat = Chat.new
  end

  def edit
  end

  def create
    @chat = Chat.new(chat_params)

   respond_to do |format|
    if @chat.save 
      UserChat.create(chat: @chat, user: current_user)
    format.turbo_stream { render turbo_stream: turbo_stream.append("user_#{current_user.id}_chats", partial: 'shared/chat', locals: {chat: @chat})}
    else 
      format.turbo_stream { render turbo_stream: turbo_stream.replace('chat_form', partial:'chats/form', locals: {chat: @chat})}
    end
   end 
  end

  def update
    respond_to do |format|
      if @chat.update chat_params
      format.turbo_stream { render turbo_stream: turbo_stream.replace("chat_#{@chat.id}", partial: 'shared/chat', locals: {chat: @chat})}
      else 
        format.html { render :edit }
      end
     end
  end

  def destroy
  end

  def add_user
    UserChat.create(chat_id: params[:chat_id], user_id: params[:user_id])
 
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("chat_show_#{params[:chat_id]}", partial: 'chats/chat', locals: {chat: Chat.find(params[:chat_id])})} 
      end
    end

  private
    def set_chat
      @chat = Chat.find(params[:id])
    end

    def chat_params
      params.require(:chat).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
  before_action :set_chat, only: %i[create edit]
  before_action :set_message, only: %i[edit update destroy]

def create 
  @message = @chat.messages.new message_params 
  @message.user = current_user

  respond_to do |format|
   if @message.save 
     format.turbo_stream
   end
  end
end

def edit;  end 

def update 
  respond_to do |format|
    if @message.update message_params
      format.turbo_stream
    end
   end
end

def destroy 
@message.destroy

respond_to do |format|
    format.turbo_stream
 end
end

private

def set_chat 
@chat = Chat.find(params[:chat_id])
end

def set_message 
@message = Message.find(params[:id])
end

def message_params 
params.require(:message).permit(:message)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<section class= "flex flex-col gap-2 mt-10 items-center justify-center" id="chat_show_<%= "#{chat.id}" %>">
   <div class= "flex flex-col">
    <h3 class= "font-bold text-3x1 text-white"><%= chat.name %> - Chat </h3>
  <span class= "text-white font-semibold">Users in this chat: </span>
</div>

<section class= "flex gap-5">
  <div class="py-2 px-10 flex flex-col gap-1 items-center border-sky-600 border rounded-1g my-2 shadow-1g w-96">
   <H3 class="text-white font-semibold text-center">Users in this chat</H3>

<% User.all.each do |user| %>
  <% next unless chat.users.include?(user) %>
   <div class="rounded underline text-white my-1 font-semibold text-sm">
     <%= user.email %>
    </div>
   <% end %>
</div>

<div class="py-2 px-10 flex flex-col gap-1 items-center border-sky-600 border rounded-1g my-2 shadow-1g w-96">
 <H3 class="text-white font-semibold text-center">Add users</H3>

<% User.all.each do |user| %>
  <% next if chat.users.include?(user) %>
    <%= button_to add_user_path, params: {user_id: user, chat_id: chat}, id: "add_user_#{user.id}", method: :post do %>
      <div class="rounded underline text-white my-1 font-semibold text-sm">
     <%= user.email %>
      </div>
     <% end %>
   <% end %>
    </div>
  </section>
</section>

app/views/chats/_form.html.erb
<div data-controller="form">   
<%= form_with(model: chat, class: "flex flex-col my-3 w-full", data: {controller: 'form', action: 'submit->form#resetComponent'}) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col gap-1 justify-center">
    <%= form.label :name, class:'text-white fond-semibold text-sm' %>
    <%= form.text_field :name, class: "w-full rounded border border-gray-300 fond-semibold text-xs" %>
  </div>

  <div class="flex mt-2 gap-2 justify-end">
    <%= form.submit class: "cursor-pointer p-2 text-sm text-white fond-semobold bg-green-400 rounded" %>
    <%= link_to 'Cancel', :back, class: "cursor-pointer p-2 text-sm text-white fond-semobold bg-red-500 rounded" %>
  </div>
<% end %>
</div>

app/views/chats/edit.html.erb
<%= turbo_frame_tag "chat_#{@chat.id}" do %>
 <h4 class="fond-medium text.base text-white text-center">Edit chat</h4>
  <%= render "form", chat: @chat %>
 <% end %>

app/views/chats/index.html.erb
 <%= turbo_frame_tag 'chats_controller' do %> 
<main class='flex w-full h-screen bg-[#86198f]'> 
  <%= render 'shared/side_bar'%>

<section class= "flex flex-col items-center justify-center gap-5 h-screen w-full"> 
    <%= image_tag("04.png", width: 100) %>
    <h1 class="font-bold text-4xl text-white my-4">VIOLETH CHAT</h1>
    <p class="text-center font-semibold text-black">CHAT LIVE</p>
  </section>
</main>
<% end %>

app/views/chats/new.html.erb
<%= turbo_frame_tag 'chat_form' do %>
 <h4 class="fond-medium text.base text-white text-center">Create New chat</h4>
  <%= render "form", chat: @chat %>
<% end %>

app/views/chats/show.html.erb
<%= turbo_frame_tag 'chats_controller' do %>
<%= turbo_stream_from 'chat_messages_channel' %>

  <main class='flex w-full h-screen bg-[#86198f]'> 
    <%= render 'shared/side_bar'%>

    <section class= "w-5/6 flex flex-col gap-5 h-screen px-5"> 
      <%= render 'chat', chat: @chat %>

      <div class= "flex flex-col w-full items-center">
        <div class= "flex flex-col w-5/6 items-center justify-center">
          <div class= "h-72 w-5/6 bg-white rounded p-2 my-5 overflow-y-auto" id="chat_messages_div">
            <% @chat.messages.order(:created_at).each do |message| %>
              <%= render 'messages/message', { message: message } %>
            <% end %>
          </div>
        </div>

         <div class= "flex flex-col w-5/6 items-center justify-center">
        <%= render 'messages/form', { chat: @chat, message: Message.new } %>
         </div>
       </div>
    </section>
  </main>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<div data-controller="form"> 
   <%= form_with(model: [chat, message], id: 'message_form', class: 'w-full flex flex-col', data: {controller: 'form', action: 'submit->form#resetComponent'}) do |f| %>
    <div class= "flex w-full">
     <%= f.text_field :message, class: 'w-full rounded shadow text-sm font-semibold border border-gray-100' %>
     <%= f.submit class: 'bg-green-500 text-white font-semibold rounded p-2' %>
   </div>
 <% end %>
</div>

app/views/messages/_message.html.erb
<%= turbo_frame_tag "message_#{message.id}", class:"bg_gray-300 px-3 py-2 flex justify-between rounded items-center gap-2 shadow" do %>
<div class= "flex gap-1">
  <span class= "text-gray-700 text-sm"><%= message.user.email %></span>
  <span class= "font-semibold text-sm"><%= message.message %></span>
</div>

<div class= "flex gap-3">
  <%= link_to edit_chat_message_path(message, chat_id: message.chat), class: 'text-sm font-medium bg-sky-700 text-white py-1 px-3 rounded' do %>
    Edit
   <% end %>

     <%= button_to chat_message_path(message.chat, message), class: 'text-sm font-medium bg-red-700 text-white py-1 px-3 rounded',  method: :delete do %>
    Delete
   <% end %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag "message_#{@message.id}", class:"bg_gray-300 px-3 py-2 flex justify-between rounded items-center gap-2 shadow" do %>
 <%= render 'messages/form', { chat: @chat, message: @message } %>
 <% end %>

app/views/shared/_chat.html.erb
<%= turbo_frame_tag "chat_#{chat.id}" do %>
 <div class="text-white font-semibol">
  <%= link_to chat_path(chat), class: 'font-semibold text-white text-sm', data: {turbo_frame: 'chats_controller'} do %>
  <%= chat.name %>
    <% end %>
  <%= link_to 'Edit chat', edit_chat_path(chat) %>
 </div>
<% end %>

app/views/shared/_create_chat.html.erb
<%= turbo_frame_tag 'chat_form' do %>
  <section class="flex flex-col items-center justify-center gap-2 mb-5">
    <h3 class="text-white fond-semibold text-sm text-center">want to start a new conversation</h3>
    <%= link_to new_chat_path, id: 'new_chat', class:'px-3 py-1 bg-black text-white fond-semibold text-sm' do %>
     Create new Chat
   <% end %>
</section>
<% end %>

app/views/shared/_side_bar.html.erb
<%= turbo_stream_from 'users_chats_channel'%>
<%= turbo_stream_from 'chat_details_channel'%>
   <nav class=" w-60 flex flex-col items-center justify-between border border-gray">
   <%= render 'shared/user_chats' %>
  <%= render 'shared/create_chat' %>
</nav>

app/views/shared/_user_chats.html.erb
<section class="flex flex-col w-full">  
<span class="text-white text-center font-semibold mt-5"><%= current_user.email %></span>
<div class= 'flex items-center justify-center mt-2'>
<%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { turbo: false }, class:'px-3 py-1 text-white bg-red-400 rounded font-semibold text-sm' %>
</div>
  <h3 class="text-white fond-bold text-xl mt-3 text-center mb-2">My chats</h3>

   <div class="flex flex-col px-5 gap-2 w-full" id="user_<%= current_user.id %>_chats">
     <% current_user.chats.all.each do |chat| %>
     <%= render 'shared/chat', { chat: chat } %>
     <% end %>
  </div>
</section>